DO $$ BEGIN
  CREATE TYPE "HeavyMetalsResult" AS ENUM ('NUMERIC', 'PASS_FAIL', 'NONE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "TestScope" AS ENUM ('FINISHED_PRODUCT', 'INGREDIENT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "CoaIssuer" AS ENUM ('INDEPENDENT_LAB', 'MANUFACTURER', 'BRAND');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE "Product"
  ADD COLUMN IF NOT EXISTS "coaVerified" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "coaIssuer" "CoaIssuer",
  ADD COLUMN IF NOT EXISTS "coaReportDate" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "labNamedOnCoa" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "coaBatchIdentified" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "heavyMetalsResult" "HeavyMetalsResult",
  ADD COLUMN IF NOT EXISTS "heavyMetalsScope" "TestScope",
  ADD COLUMN IF NOT EXISTS "microbialPanel" BOOLEAN NOT NULL DEFAULT false;
